INSERT INTO FormGroup (FormGroupId,FormGroupName,[Order],Active) VALUES
('firstform',    'First Form',1,1),         
('scfflft',	'Sample Collection Form for Liver function test',2,1),  
('cimef',	'Check-in Medical Examination Form',3,1  ),
('pccf',		'Protocol compliance confirmation form',4,1  ),
('inclusionc',	'Inclusion Criteria',5,1),
('inclusioncf',	'Inclusion Criteria Female',6,1),
('exclusionc',	'Exclusion Criteria',7,1),
('eligibilityc',	'Eligibility Confirmation',8,1),
('checkinf',	'Check-in form',9,1),
('mealsf',	'Meals form',10 ,1),
('mealsfc',	'Meals form (Cont.)',11,1),
('sfcdaf',	'Suitability for concomitant drug administration form',12,1),
('cma',		'Concomitant medication administration',13,1),
('sfdaf',	'Suitability for drug administration form',14,1),
('daf',		'Drug administration form',15,1),
('rap',		'Restrictions and Prohibitions',16,1),
('120waf',	'120 mL of water administration form',17,1),
('soatwd01hpda','Supervision of access to washroom during 01 hour post drug administration',18,1),
('vf',		'Vitals form',19,1),
('vawbrf',	'Vitals and well-being record form',20,1),
('ecgf',		'ECG form',21,1),
('cmf',		'Cardiac monitoring form',22,1),
('wbf',		'Well-being form',23,1),
('ivcirf',	'IV cannula insertion / removal form',24,1),
('robs',		'Record of Blood Sampling',25,1),
('robsc',	'Record of Blood Sampling (Cont.)',26,1),
('60gsaf',	'60 ml of 20% glucose solution administration form',27,1),
('bgmr',	'Blood glucose monitoring Record',28,1),
('comef',	'Check-out Medical Examination Form',29,1),
('cof',		'Check-out form',30,1),
('cofc',		'Check-out form (Cont.)',31,1)