//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRFDetail
    {
        public int DetailsId { get; set; }
        public int StudyId { get; set; }
        public string SubjectId { get; set; }
        public string ScreeningNo { get; set; }
        public string RegisteredNo { get; set; }
        public int Status { get; set; }
        public string ProtocoTitle { get; set; }
    }
}
