//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormField
    {
        public string FormId { get; set; }
        public string FieldId { get; set; }
        public string FieldLiteral { get; set; }
        public string FieldExportName { get; set; }
        public int PeriodId { get; set; }
        public string FormGroupId { get; set; }
        public int StudyId { get; set; }
        public string FieldDataType { get; set; }
        public string FieldType { get; set; }
        public bool FieldMandatory { get; set; }
        public Nullable<int> Order { get; set; }
        public bool Display { get; set; }
        public bool Disabled { get; set; }
        public string Unit { get; set; }
        public string LOVId { get; set; }
    }
}
