//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormGroupPeriod
    {
        public string FormGroupId { get; set; }
        public int PeriodId { get; set; }
        public Nullable<int> Order { get; set; }
        public int StudyId { get; set; }
        public string PageRef { get; set; }
        public bool Active { get; set; }
    }
}
