//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListOfValuesbkup
    {
        public string LOVId { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> Active { get; set; }
        public string temp { get; set; }
    }
}
