//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOVStudyStatu
    {
        public int StudyStatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
