//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StepCinemaDataLayer.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public int StudyId { get; set; }
        public string StudyNumber { get; set; }
        public string StudyName { get; set; }
        public int NoOfPeriods { get; set; }
        public string SiteId { get; set; }
        public int StudyStaus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool Active { get; set; }
    }
}
